# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0003_auto_20191010_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lacation',
            new_name='location',
        ),
    ]
